### ISSUE TITLE
Show generated MDX query

### ISSUE THREAD

**Issue by rusvdw** [rpbouman/xavier#23]
It would be great to optionally have the MDX query that is being submitted to XML/A displayed. It's super useful as a learning tool. It would also be nice to be able to modify and execute MDX directly.

**Comment by rpbouman** [comment]
Hi Rusvdw!

Thanks for your interest! 

There is an exising feature request for this: https://github.com/rpbouman/xavier/issues/5 The idea is to have a special "visualization" tab that is basically a log of what's happening on the XML/A front, along with timing info. 

For entering MDX statements directly, I would like to point you to pash. This is a web-based MDX shell that is based on the same technology as Xavier - XML/A using the xmla4js library. 

Pash is here on github: https://github.com/rpbouman/pash 
Here's a video of pash in action: https://www.youtube.com/watch?v=9ieDY6Yedn4

In the vid it is deployed inside Pentaho, but it works just as well on other XML/A providers. 

I also prepared xmondrian, which is a .WAR (web archive) containing mondrian, a sample mondrian schema based on the foodmart database, and an embedded database to work on. This bundles both xavier as well as pash (re-branded as xmlash). You can find that here:

https://github.com/rpbouman/xmondrian

Feel free to drop me a line if you need help to get started with xmlash: roland.bouman@gmail.com

I will now close this request, since it is duplicate. Feel free to add any specific requirements to that prior issue https://github.com/rpbouman/xavier/issues/5

Thanks in advance!

Roland.

**Comment by rusvdw** [comment]
Thanks Roland. I've tried xmlash (thanks for xmondrian btw!), but the use case I'm after is one where I try out some queries visually using drag and drop and get to incrementally modify them to see how they work. Sorta like Saiku, but hopefully less frustrating. I'll keep following your progress though!

**Comment by rpbouman** [comment]
Hi @rusvdw !

Ok! Fair enough. Well you're not the first one that expressed their desire for a "grab the MDX" functionality in xavier, so it should be built. 

If you could spare a moment, and hop over to that original issue https://github.com/rpbouman/xavier/issues/5, and add comments there to provide as much details as to how you would like it to work, then I can work with that. 

Cheers, and thanks in advance,

Roland
